CREATE TABLE clients (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

CREATE TABLE contacts (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
contact_value VARCHAR(255) NOT NULL,
contact_type VARCHAR(20) NOT NULL,
client_id INTEGER REFERENCES clients(id)
);

INSERT INTO clients (name)
VALUES ('Иванов Адам Сергеевич'),
       ('Кучер Алена Игоревна'),
       ('Викторов Эрнест Александрович');

INSERT INTO contacts (contact_value, contact_type, client_id)
VALUES
    ('ivanov@gmail.com', 'EMAIL', '1'),
    ('alenakucher@mail.ru', 'EMAIL', '2'),
    ('89789653464', 'PHONE', '2'),
    ('+79654568769', 'PHONE', '3');

